### ISSUE TITLE
Any way to install with Home Assistant Core, not as an add-on?

### ISSUE THREAD

**Issue by oscargala** [starsoccer/energysmartbridge#5]
I'm running Home Assistant Core on an Ubuntu server with MQTT and suck in docker containers.  Is there any way to run this repo in docker as well without using the HA Add-on install method as that's not available in Core?

**Comment by oscargala** [comment]
Got it to work

**Comment by mattserpe** [comment]
I am also interested in running this via vanilla Docker, preferably with Docker Compose. @oscargala are you able to share any info regarding how you were able to do this?

@starsoccer if you have any guidance on this from your experience in building this add-on, that would be greatly appreciated as well.

Thank you both in advance!

**Comment by mefbgil** [comment]
I'm running this plain docker.  My router doesn't support c-name DNS entries, so I have a Macvlan interface to front the IP address and a-names DNS entries, 2 ha-proxy containers, 1 for each of those, then 1 container for energysmart, and then the standard connectivity to MQTT.  Here are the compose files, ha-proxy configs, and options.json you'll need for energysmart to function.

Here's the command line I use to build the image.

```shell
cd /data/mnt/docker/energysmart/git/starsoccer/master/ && git clone --branch master https://github.com/starsoccer/energysmartbridge.git && cd energysmartbridge/energysmartbridge/ && sudo docker image prune -af && sudo docker build --no-cache -f ./Dockerfile -t energysmartbridge .
``` 

[energysmart-docker-compose-yml.txt](https://github.com/user-attachments/files/19405922/energysmart-docker-compose-yml.txt)
[haproxy-docker-compose-yml.txt](https://github.com/user-attachments/files/19405919/haproxy-docker-compose-yml.txt)
[options-json.txt](https://github.com/user-attachments/files/19405920/options-json.txt)
[haproxy-9-cfg.txt](https://github.com/user-attachments/files/19405921/haproxy-9-cfg.txt)
[haproxy-8-cfg.txt](https://github.com/user-attachments/files/19405923/haproxy-8-cfg.txt)

**Comment by mattserpe** [comment]
Thanks for the quick reply, @mefbgil !

I finally got a chance to build and deploy my container today. It seems to be working but I am observing weird behavior from the smart sensor itself and curious if anyone has seen/resolved this issue before?

Basically, when energysmartbridge is running with trace logging enabled, I only ever see a single message from the energysmart device logged. This message arrives only when I reset the energysmart device on my water heater and reconnect it to my wifi network. Once it is connected to wifi, I see a single set of message logs, then no additional logs at any point after until I reset the device again. I have waited hours, used more hot water, and no matter how long I wait, I never see another message. I have tried all of the modes available on my water heater for monitoring that I know of, but same behavior either way, other than the value of the "Grid" variable reported in the message.

Here is a sample of my logs after I start energysmartbridge, reset the energysmart device on my water heater in one of the modes, then reset again a little later in the other mode. After this set of logs was generated, it has been many more hours and still no more logs seen.

```
# energysmartbridge startup
Setting ENV Variables
Env Set
Listing Versions!
nginx version: nginx/1.24.0
Node Version: v12.22.12
NPM Version: 7.5.2
(node:21) Warning: Currently the require() provided to the main script embedded into single-executable applications only supports loading built-in modules.
To load a module from disk after the single executable application is launched, use require("module").createRequire().
Support for bundled module loading or virtual file systems are under discussions in https://github.com/nodejs/single-executable
(Use `app --trace-warnings ...` to show where the warning was created)
{"level":20,"time":1742766611315,"pid":21,"hostname":"<HOSTNAME_REDACTED>","message":"Loaded Config"}
(node:21) ExperimentalWarning: Single executable application is an experimental feature and might change at any time
{"level":30,"time":1742766612181,"pid":21,"hostname":"<HOSTNAME_REDACTED>","message":"Server listening on 8001"}

# Log of request received when RA showing on water heater display and energysmart device reset and reconnected to wifi
{"level":20,"time":1742769353773,"pid":21,"hostname":"<HOSTNAME_REDACTED>","message":"Got Request","body":{"DeviceText":"<TEXT_REDACTED>","Password":"<PASS_REDACTED>","ModuleApi":"1.5","ModFwVer":"3.1","MasterFwVer":"02.06","MasterModelId":"B2.00","DisplayFwVer":"00.00","WifiFwVer":"C2.4.0.3.AO7","UpdateRate":"300","Mode":"Hybrid","SetPoint":"130","Units":"F","LeakDetect":"NotDetected","MaxSetPoint":"130","Grid":"Disabled","AvailableModes":"Efficiency,Hybrid,Electric,Vacation","SystemInHeating":"False","HotWaterVol":"High","Leak":"None","DryFire":"None","ElementFail":"None","TankSensorFail":"None","EcoError":"False","MasterDispFail":"None","CompSensorFail":"None","SysSensorFail":"None","SystemFail":"None","CondensePumpFail":"False","AirFilterStatus":"OK","UpperTemp":"127","LowerTemp":"125","FaultCodes":"0","UnConnectNumber":"0","AddrData":"05FD|00AF","SignalStrength":"-69"},"path":"/~branecky/postAll.php"}
{"level":10,"time":1742769353778,"pid":21,"hostname":"<HOSTNAME_REDACTED>","message":"Setting device id","deviceId":"<TEXT_REDACTED>"}
{"level":10,"time":1742769353778,"pid":21,"hostname":"<HOSTNAME_REDACTED>","message":"Got Unit","unit":"°F"}
{"level":10,"time":1742769353780,"pid":21,"hostname":"<HOSTNAME_REDACTED>","message":"Converting key","key":"DeviceText"}
{"level":10,"time":1742769353780,"pid":21,"hostname":"<HOSTNAME_REDACTED>","message":"Converting key","key":"Password"}
{"level":10,"time":1742769353781,"pid":21,"hostname":"<HOSTNAME_REDACTED>","message":"Converting key","key":"ModuleApi"}
{"level":10,"time":1742769353782,"pid":21,"hostname":"<HOSTNAME_REDACTED>","message":"Converting key to sensor","key":"ModuleApi"}
{"level":10,"time":1742769353786,"pid":21,"hostname":"<HOSTNAME_REDACTED>","message":"Checking if unit is set"}
{"level":10,"time":1742769353787,"pid":21,"hostname":"<HOSTNAME_REDACTED>","message":"Publishing config","topic":"homeassistant/sensor/<TEXT_REDACTED>/moduleAPI/config","name":"moduleAPI"}

# Log of request received when 'rising lines' animation showing on water heater display and energysmart device reset and reconnected to wifi
{"level":20,"time":1742770152595,"pid":21,"hostname":"<HOSTNAME_REDACTED>","message":"Got Request","body":{"DeviceText":"<TEXT_REDACTED>","Password":"<PASS_REDACTED>","ModuleApi":"1.5","ModFwVer":"3.1","MasterFwVer":"02.06","MasterModelId":"B2.00","DisplayFwVer":"00.00","WifiFwVer":"C2.4.0.3.AO7","UpdateRate":"300","Mode":"Hybrid","SetPoint":"130","Units":"F","LeakDetect":"NotDetected","MaxSetPoint":"130","Grid":"Enabled","AvailableModes":"Efficiency,Hybrid,Electric,Vacation","SystemInHeating":"False","HotWaterVol":"High","Leak":"None","DryFire":"None","ElementFail":"None","TankSensorFail":"None","EcoError":"False","MasterDispFail":"None","CompSensorFail":"None","SysSensorFail":"None","SystemFail":"None","CondensePumpFail":"False","AirFilterStatus":"OK","UpperTemp":"125","LowerTemp":"125","FaultCodes":"0","UnConnectNumber":"0","AddrData":"05FD|00AF","SignalStrength":"-70"},"path":"/~branecky/postAll.php"}
{"level":10,"time":1742770152596,"pid":21,"hostname":"<HOSTNAME_REDACTED>","message":"Setting device id","deviceId":"<TEXT_REDACTED>"}
{"level":10,"time":1742770152596,"pid":21,"hostname":"<HOSTNAME_REDACTED>","message":"Got Unit","unit":"°F"}
{"level":10,"time":1742770152597,"pid":21,"hostname":"<HOSTNAME_REDACTED>","message":"Converting key","key":"DeviceText"}
{"level":10,"time":1742770152597,"pid":21,"hostname":"<HOSTNAME_REDACTED>","message":"Converting key","key":"Password"}
{"level":10,"time":1742770152597,"pid":21,"hostname":"<HOSTNAME_REDACTED>","message":"Converting key","key":"ModuleApi"}
{"level":10,"time":1742770152597,"pid":21,"hostname":"<HOSTNAME_REDACTED>","message":"Converting key to sensor","key":"ModuleApi"}
{"level":10,"time":1742770152597,"pid":21,"hostname":"<HOSTNAME_REDACTED>","message":"Checking if unit is set"}
{"level":10,"time":1742770152598,"pid":21,"hostname":"<HOSTNAME_REDACTED>","message":"Publishing config","topic":"homeassistant/sensor/<TEXT_REDACTED>/moduleAPI/config","name":"moduleAPI"}
```


For context, my full setup is Pi-Hole as DNS + Home Assistant + Eclipse Mosquitto + EnergySmartBridge all running on the same Raspberry Pi 3B and launched via docker compose.


While I think this may be an unrelated issue, I also notice energysmartbridge says "Publishing config", but I do not see any associated logs in mosquitto or in home assistant after this log so I am wondering if energysmartbridge is having an issue sending and is halted because of this and not able to collect any additional logs. Again, not sure if these two issues are related and I don't see any errors indicating that they might be but including it in case it is relevant for diagnosis.

I have attached my docker-compose.yml and my options.json, but please let me know if any other pieces of info might be helpful for diagnosis.

[docker-compose-yml.txt](https://github.com/user-attachments/files/19413444/docker-compose-yml.txt)

[options.json](https://github.com/user-attachments/files/19413427/options.json)

**Comment by starsoccer** [comment]
@mattserpe Sorry for the delay. first can you make sure your pulling the latest as I have fixed some bugs from a week or two back. Next assuming your on the latest, if you have any logs can you create a new issue and post them there?

From the logs posted everything seems to be ok. The fact the sensor is only connecting once then stopping randomly is indeed odd. Iy makes me think its not connecting successfully for some reason. For sanity sake it may be worth using a tool like postman to simulate making the request your self and verifying everything works.

Happy to help further if needed.
